# Generated by Django 5.1.7 on 2025-03-19 21:37

from django.db import migrations

def add_sample_products(apps, schema_editor):
    Product = apps.get_model('accounts', 'Product')
    
    products = [
        {
            'name': 'ولکین مون',
            'description': '',
            'price': '430.000',
            'stock': 2,
            'image_url': 'https://imgs.search.brave.com/0ULGEEYysK9FxtCCqQlrEP9YrQ_Ly7VnlfQb8Xlssyg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9paDEu/cmVkYnViYmxlLm5l/dC9pbWFnZS4yMjMw/OTI2MTY0LjYxNDUv/ZmxhdCw3NTB4LDA3/NSxmLXBhZCw3NTB4/MTAwMCxmOGY4Zjgu/anBn'
        },
        {
            'name': '980 تا جنسیس کریستال',
            'description': 'RGB mechanical keyboard with Cherry MX Blue switches',
            'price': '129.99',
            'stock': 50,
            'image_url': 'https://image.api.playstation.com/vulcan/img/rnd/202104/2507/KrSyIaYnUhxEosDimmMW3JeL.png?w=54&thumb=true'
        },
        {
            'name': 'Gaming Mouse',
            'description': '16000 DPI gaming mouse with programmable buttons',
            'price': '79.99',
            'stock': 100,
            'image_url': 'https://example.com/mouse.jpg'
        },
        {
            'name': '4K Gaming Monitor',
            'description': '27-inch 4K monitor with 144Hz refresh rate and HDR',
            'price': '599.99',
            'stock': 15,
            'image_url': 'https://example.com/monitor.jpg'
        },
        {
            'name': 'Gaming Headset',
            'description': '7.1 surround sound gaming headset with noise-canceling mic',
            'price': '149.99',
            'stock': 30,
            'image_url': 'https://example.com/headset.jpg'
        },
        {
            'name': 'Gaming Chair',
            'description': 'Ergonomic gaming chair with lumbar support and adjustable armrests',
            'price': '299.99',
            'stock': 20,
            'image_url': 'https://example.com/chair.jpg'
        },
        {
            'name': 'RTX 4090 Graphics Card',
            'description': 'NVIDIA GeForce RTX 4090 24GB GDDR6X graphics card',
            'price': '1499.99',
            'stock': 5,
            'image_url': 'https://example.com/gpu.jpg'
        },
        {
            'name': 'Gaming PC Case',
            'description': 'Mid-tower case with tempered glass and RGB fans',
            'price': '129.99',
            'stock': 25,
            'image_url': 'https://example.com/case.jpg'
        }
    ]
    
    for product_data in products:
        Product.objects.create(**product_data)

def remove_sample_products(apps, schema_editor):
    Product = apps.get_model('accounts', 'Product')
    Product.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_products, remove_sample_products),
    ]
